# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  # Define conda-forge packages here -> https://anaconda.org/search
  # When available, prefer the conda-forge packages over pip as installations are more efficient.
  - python=3.9.13               # https://pyreadiness.org/3.9/ 
  - pip=22.1.2                  # https://pip.pypa.io/en/stable/news/
  - pip:
      # Define pip packages here -> https://pypi.org/
      - rpaframework==22.0.0    # https://rpaframework.org/releasenotes.html
      - robotframework-appiumlibrary==2.0.0
      - zxing==0.14
      - robotframework-selenium2library==3.0.0
      - webdriver-manager==3.8.5
      - async-generator==1.10
      - attrs==22.2.0
      - certifi==2022.12.7
      - cffi==1.15.1
      - charset-normalizer==3.1.0
      - chromedriver-binary-auto==0.2.3
      - colorama==0.4.6
      - decorator==5.1.1
      - distlib==0.3.6
      - docutils==0.19
      - filelock==3.9.0
      - h11==0.14.0
      - idna==3.4
      - install==1.3.5
      - kitchen==1.2.6
      - outcome==1.2.0
      - packaging==23.0
      - platformdirs==3.0.0
      - pycparser==2.21
      - PySocks==1.7.1
      - python-dotenv==1.0.0
      - six==1.16.0
      - sniffio==1.3.0
      - sortedcontainers==2.4.0
      - tqdm==4.65.0
      - trio==0.22.0
      - trio-websocket==0.9.2
      - urllib3==1.26.14
      - virtualenv==20.19.0
      - wsproto==1.2.0
      