*** Settings ***
Resource    ../com.playgroundxyz.vision_project.PageObject.locators/Locators.resource
Resource    Allow Permission page keywords.resource
Resource    LetsSetupYourEyeTrackingKeywords.resource
Resource    welcome page journey keywords.resource
Resource    QR_Code_page_keywords.resource
Resource    Setup keywords.resource
Resource    EyeGazeValiidationKeywords.resource
Resource    launch_flow_keywords.resource
